services:
  postgres:
    container_name: ms_pg-sql
    image: postgres
    environment:
      POSTGRES_USER: bobrox
      POSTGRES_PASSWORD: bobrox
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - "mongodb"
  #  volumes:
  #    mongo-data:
  #      driver: local

  #  mongodb:
  #    container_name: mongodb
  #    image: mongo:7.0.5
  #    ports:
  #      - "27017:27017"
  #    volumes:
  #      - mongo:/data/db
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: password
  #    restart: unless-stopped

  #  mongo-express:
  #    container_name: ms_mongo_express
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    environment:
  #      - ME_CONFIG_MONGO_ADMINUSERNAME=bobrox
  #      - ME_CONFIG_MONGO_ADMINPASSWORD=bobrox
  #      - ME_CONFIG_MONGO_SERVER=mongodb
  #      - ME_CONFIG_HOSTNAME=mongodb
  #      - ME_CONFIG_MONGO_AUTH_DATABASE=admin

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo-data:
    driver: local
